name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: portfolio-site-492218
  REGION: us-east1
  SERVICE: portfolio-site
  REPO: portfolio-repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build and push image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$SERVICE \
            --push .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$SERVICE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated